version: '3'
services:
  frontend:
    tty: true
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    tty: true
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app